services:
  - type: web
    name: fno-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"  # Replace app.py with the name of your script
    port: 8050